# 行列

## NumPy ndarray

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]])

In [3]:
A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
print(A)
print(A.shape)
print(A.ndim)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
(3, 3)
2


## SymPy Matrix

In [5]:
import sympy as sy

In [6]:
B = sy.Matrix([[1, 4, 7],
                 [2, 5, 8],
                 [3, 6, 9]])

In [7]:
B

Matrix([
[1, 4, 7],
[2, 5, 8],
[3, 6, 9]])

In [8]:
print(B)
print(B.shape)

Matrix([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
(3, 3)
